version: '3'
services:
  ztsphp:
    build: ${PWD}/ztsphp
    container_name: ztsphp
    volumes:
      - ${PWD}/ztsphp:/var/www/html

  nginx:
    build: ${PWD}/nginx
    container_name: nginx
    ports:
      - 81:80
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx:/var/www/html
    depends_on:
      - ztsphp

  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - 4444:4444

  chrome1:
    image: selenium/node-chrome-debug:3.141.59-xenon
    container_name: chrome1
    ports:
      - 5900:5900
    links:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  chrome2:
    image: selenium/node-chrome-debug:3.141.59-xenon
    container_name: chrome2
    ports:
      - 5901:5900
    links:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

#  chrome3:
#    image: selenium/node-chrome-debug:3.141.59-xenon
#    container_name: chrome3
#    ports:
#      - 5902:5900
#    links:
#      - selenium-hub
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#
#  chrome4:
#    image: selenium/node-chrome-debug:3.141.59-xenon
#    container_name: chrome4
#    ports:
#      - 5903:5900
#    links:
#      - selenium-hub
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#
#  chrome5:
#    image: selenium/node-chrome-debug:3.141.59-xenon
#    container_name: chrome5
#    ports:
#      - 5904:5900
#    links:
#      - selenium-hub
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#
#  chrome6:
#    image: selenium/node-chrome-debug:3.141.59-xenon
#    container_name: chrome6
#    ports:
#      - 5906:5900
#    links:
#      - selenium-hub
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#
#  chrome7:
#    image: selenium/node-chrome-debug:3.141.59-xenon
#    container_name: chrome7
#    ports:
#      - 5907:5900
#    links:
#      - selenium-hub
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#
#  chrome8:
#    image: selenium/node-chrome-debug:3.141.59-xenon
#    container_name: chrome8
#    ports:
#      - 5910:5900
#    links:
#      - selenium-hub
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
